steps:
  - name: python:3.10
    id: "Install + Run script"
    entrypoint: bash
    args:
      - -c
      - |
        pip install --no-cache-dir --upgrade jupyter google-cloud-storage
        python utils/Github_To_Bucket_Composer.py
    env:
      - BUCKET_NAME=$_BUCKET_NAME

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s

substitutions:
  _BUCKET_NAME: us-east1-paris-opendata-com-baec303d-bucket