project_id = "paris-opendata-gcp"
region     = "europe-west1"
env = "dev"
zone  = "europe-west1-b"
cluster = "paris-opendata-cluster"
dataproc_service_account = "terraform-admin@paris-opendata-gcp.iam.gserviceaccount.com"